site_name: 10 Birr

# Theme
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.code.select
    - content.code.annotate
  
  palette: 
    - media: "(prefers-color-scheme: light)" # Light mode 
      scheme: default
      primary: white
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)" # Dark mode
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  icon:
    logo: material/numeric-10
    favicon: images/favicon.png

nav:
  - Home: index.md
  - athenaSQL: athenaSQL/index.md 
  - Cookbooks: 
    - cookbooks/index.md 
    - Bash: cookbooks/bash.md
    - Javascript: cookbooks/javascript.md
    - Python: cookbooks/python.md
  - Blog:
    - blog/index.md
  - About: about.md

markdown_extensions:
  # Admonition
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


plugins:
  - search
  - blog
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
