site_name: 10 BIRR 
site_url: https://nabilseid.github.io
site_description: I blend in my open source projects and notes.
copyright: Made with ❤️  in Medeja Bet

use_directory_urls: true

# Theme
theme:
  name: material
  custom_dir: overrides

  features:
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.code.select
    - content.code.annotate
  
  palette: 
    - media: "(prefers-color-scheme: light)" # Light mode 
      scheme: default
      primary: white
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)" # Dark mode
      scheme: slate
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  
  icon:
    logo: fontawesome/solid/mountain-sun

  favicon: 'assets/images/favicon.png'

nav:
  - Home: index.md
  - athenaSQL: 
    - athenaSQL/index.md 
    - Databases & Tables: athenaSQL/databases_and_tables.md
    - Columns: athenaSQL/columns.md
    - Queries:
      - athenaSQL/queries/index.md
      - SELECT: athenaSQL/queries/select.md
      - INSERT INTO: athenaSQL/queries/insert_into.md
      - CREATE: athenaSQL/queries/create.md
      - CREATE AS: athenaSQL/queries/create_as.md
      - CTE: athenaSQL/queries/cte.md
      - UNLOAD: athenaSQL/queries/unload.md
      - WINDOW: athenaSQL/queries/window.md
    - Functions:
      - athenaSQL/functions/index.md
      - Aggregation Functions: athenaSQL/functions/aggregation.md
      - String Functions: athenaSQL/functions/string.md
      - Date and Time Functions: athenaSQL/functions/date_time.md
      - URL Functions: athenaSQL/functions/url.md
      - Window Functions: athenaSQL/functions/window.md
      - Unicode Functions: athenaSQL/functions/unicode.md
      - UUID Functions: athenaSQL/functions/uuid.md

  - Cookbooks: 
    - cookbooks/index.md 
    - Bash: cookbooks/bash.md
    - Javascript: cookbooks/javascript.md
    - Python: cookbooks/python.md
  - Blog:
    - blog/index.md
  # - The Universe: 
  #   - the-universe/index.md
  #   - Our kids and Them Kids: the-universe/our-kids-and-them-kids.md
  - Resume: resume.md

markdown_extensions:
  # Admonition
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  # Code blocks
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

  # formatting
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  
  # lists
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nabilseid
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/nabilseid
    - icon: fontawesome/brands/telegram
      link: https://t.me/nabilseid
    - icon: fontawesome/solid/paper-plane
      link: mailto:<nabeelseid@gmail.com>

plugins:
  - search
  - blog
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - categories
        - tags
